### ISSUE TITLE
使用阿里云RDS配置提示:You not set a config array for connect!

### ISSUE THREAD

**Issue by kingleoric** [owner888/phpspider#119]
外网权限都没问题,用navicat都可以打开,但是程序跑不起来

提示`Fatal error: Uncaught Exception: You not set a config array for connect! in /mnt/www/***/core/queue.php:110
Stack trace:
#0 /mnt/www/***/core/phpspider.php(824): phpspider\core\queue::set_connect('default', Array)
#1 /mnt/www/***/work/xxxx.com.php(265): phpspider\core\phpspider->start()
#2 {main}
  thrown in /mnt/www/***/core/queue.php on line 110`

看到 queue.php第110行,这里好像是$link_name的问题?
`            if (empty(self::$configs[self::$link_name]))
            {
                throw new Exception("You not set a config array for connect!");
            }`

@owner888  请问大大怎么回事?

**Comment by kingleoric** [comment]
环境是PHP7

**Comment by kingleoric** [comment]
这是数据库配置`    'db_config' => array(
        'host'  => 'rm-****.mysql.****.rds.aliyuncs.com',
        'port'  => 3306,
        'user'  => '****',
        'pass'  => '****',
        'name'  => '****',
    ),`

**Comment by kingleoric** [comment]
是队列设置的问题,已经解决了,之前在本地win10上面跑,后来部署到centos上,配置还是有点差异的! 

谢谢各位关注
