### ISSUE TITLE
css选择器是不是不行

### ISSUE THREAD

**Issue by valiner** [owner888/phpspider#82]

**Comment by owner888** [comment]
可以的啊，什么问题呢 ？

**Comment by valiner** [comment]
很奇怪 我之前一个PHP脚本放在TP5下可以运行，放在Laravel 就报
`PHP Fatal error:  Uncaught Exception: You not set a config array for connect! in E:\Homestead\code\lol\vendor\owner888\phpspider\core\queue.php:110
Stack trace:
#0 E:\Homestead\code\lol\vendor\owner888\phpspider\core\phpspider.bak20170807.php(1000): phpspider\core\queue::set_connect('default', Array)
#1 E:\Homestead\code\lol\vendor\owner888\phpspider\core\phpspider.bak20170807.php(952): phpspider\core\phpspider->do_collect_page()
#2 E:\Homestead\code\lol\get_news.php(142): phpspider\core\phpspider->start()
#3 {main}
  thrown in E:\Homestead\code\lol\vendor\owner888\phpspider\core\queue.php on line 110`

但是我还没有使用set_connect函数

**Comment by valiner** [comment]
已解决原来没有加redis的配置，但是之前没加也可以运行。

**Comment by haoyoul** [comment]
css最后换成了xpath  这不是骗人吗。
 ```
 private static function _css_select($html, $selector, $remove = false)  //selecter.php 177行
{
        $selector = self::css_to_xpath($selector);
        return self::_xpath_select($html, $selector, $remove);
｝
```
